### ISSUE TITLE
Unable to setup phpsocket.io with Docker

### ISSUE THREAD

**Issue by binemmanuel** [walkor/phpsocket.io#283]
### Dockerfile.socket
```
FROM php:8.1.13-cli

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
CMD php /app/src/socket.php start -d
```

### docker-compose.yaml
```
socket:
        build:
            context: .
            dockerfile: Dockerfile.socket

        depends_on:
            - database

        ports:
            - 8181:8181

        networks:
            - some-network
```
